name: Deploy GitHub

on: [ push ]

jobs:
  build:
    container: 
      image: "emscripten/emsdk:3.1.8"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: sh ./build-web.sh release

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Release/Web/Dist
          keep_files: true
